# Generated by Django 4.1.5 on 2023-03-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='sahr', upload_to='image'),
            preserve_default=False,
        ),
    ]
