# Generated by Django 4.1.5 on 2023-03-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0002_movies_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='img',
            new_name='imgg',
        ),
    ]
