# Generated by Django 4.1.5 on 2023-03-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0004_rename_imgg_movies_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
