# Generated by Django 4.1.5 on 2023-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0005_alter_movies_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
